In [1]:
import pandas as pd

In [10]:
import numpy as np

In [2]:
from tqdm import tqdm

In [3]:
MA = pd.read_csv('..\\data\\raw\\M&APreprocessed.csv')

In [5]:
CI = pd.read_excel('..\\data\\raw\\CompanyInfoPreprocessed.xlsx')

In [55]:
count = 0
MA_D = []
for i in tqdm(range(len(MA))):
    for j in range(len(CI)):
        if MA["Acquiree Name"][i] == CI["Organization Name"][j]:
            #print(MA["Acquiree Name"][i], CI["Organization Name"][j])
            MA_D.append(np.concatenate([MA.iloc[i,:], CI.iloc[j,:]]))
            count += 1
print(count)

100%|██████████████████████████████████████████████████████████████████████████| 23622/23622 [8:32:27<00:00,  1.30s/it]

23168

In [80]:
count2 = 0
MA_Master = []
for i in tqdm(range(len(MA_D))):
    for j in range(len(CI)):
        if MA_D[i][3] == CI["Organization Name"][j]:
            #print(MA_D[i][3], CI["Organization Name"][j])
            MA_Master.append(np.concatenate([MA_D[i], CI.iloc[j,:]]))
            count2 += 1
print(count2)

100%|██████████████████████████████████████████████████████████████████████████| 23168/23168 [4:19:53<00:00,  1.49it/s]

21107

In [81]:
MA_Master[1000]

array([2012, 'BULX acquired by DealYard.com', 'BULX', 'DealYard.com',
       'BULX', 2010, 2012.0, 'DealYard.com',
       'Commerce and Shopping, Consumer Goods, Real Estate',
       'Consumer Goods, E-Commerce, Home Improvement',
       'Westbury, New York, United States',
       'Greater New York Area, East Coast, Northeastern US', 2.0, '11-50',
       nan, nan, nan, nan, 5.0, nan, nan, 14.0, nan, nan, nan,
       '$1M to $10M', 1.0, 'M&A', 240000.0, 'Seed', 240000.0, 'Seed',
       240000.0, 240000.0, nan, nan, nan, nan, nan, nan, 'DealYard.com',
       2003, nan, nan, 'Commerce and Shopping', 'E-Commerce',
       'Westbury, New York, United States',
       'Greater New York Area, East Coast, Northeastern US', 1.0, '01-10',
       2.0, 5567.0, 29.0, 2.0, 35.0, nan, nan, 18.0, nan, nan, nan,
       '$1M to $10M', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan], dtype=object)

In [82]:
column_names = ['Announced Date',
'Transaction Name',
'Acquiree Name',
'Acquirer Name',
'EE_Organization Name',
'EE_Founded Date',
'EE_Announced Date',
'EE_Acquired by',
'EE_Industry Groups',
'EE_Industries',
'EE_Headquarters Location',
'EE_Headquarters Regions',
'EE_Number of Founders',
'EE_Number of Employees',
'EE_Number of Articles',
'EE_Average Visits (6 months)',
'EE_Visit Duration',
'EE_Page Views / Visit',
'EE_Active Tech Count',
'EE_Patents Granted',
'EE_Trademarks Registered',
'EE_Total Products Active',
'EE_IT Spend Currency (in USD)',
'EE_Number of Apps',
'EE_Downloads Last 30 Days',
'EE_Estimated Revenue Range',
'EE_Number of Funding Rounds',
'EE_Funding Status',
'EE_Last Funding Amount Currency (in USD)',
'EE_Last Funding Type',
'EE_Last Equity Funding Amount Currency (in USD)',
'EE_Last Equity Funding Type',
'EE_Total Equity Funding Amount Currency (in USD)',
'EE_Total Funding Amount Currency (in USD)',
'EE_Number of Portfolio Organizations',
'EE_Number of Investments',
'EE_Number of Lead Investments',
'EE_Number of Diversity Investments',
'EE_Number of Lead Investors',
'EE_Number of Investors',
'ER_Organization Name',
'ER_Founded Date',
'ER_Announced Date',
'ER_Acquired by',
'ER_Industry Groups',
'ER_Industries',
'ER_Headquarters Location',
'ER_Headquarters Regions',
'ER_Number of Founders',
'ER_Number of Employees',
'ER_Number of Articles',
'ER_Average Visits (6 months)',
'ER_Visit Duration',
'ER_Page Views / Visit',
'ER_Active Tech Count',
'ER_Patents Granted',
'ER_Trademarks Registered',
'ER_Total Products Active',
'ER_IT Spend Currency (in USD)',
'ER_Number of Apps',
'ER_Downloads Last 30 Days',
'ER_Estimated Revenue Range',
'ER_Number of Funding Rounds',
'ER_Funding Status',
'ER_Last Funding Amount Currency (in USD)',
'ER_Last Funding Type',
'ER_Last Equity Funding Amount Currency (in USD)',
'ER_Last Equity Funding Type',
'ER_Total Equity Funding Amount Currency (in USD)',
'ER_Total Funding Amount Currency (in USD)',
'ER_Number of Portfolio Organizations',
'ER_Number of Investments',
'ER_Number of Lead Investments',
'ER_Number of Diversity Investments',
'ER_Number of Lead Investors',
'ER_Number of Investors']

In [83]:
df = pd.DataFrame(MA_Master, columns=column_names)

In [84]:
df

,Announced Date,Transaction Name,Acquiree Name,Acquirer Name,EE_Organization Name,EE_Founded Date,EE_Announced Date,EE_Acquired by,EE_Industry Groups,EE_Industries,...,ER_Last Equity Funding Amount Currency (in USD),ER_Last Equity Funding Type,ER_Total Equity Funding Amount Currency (in USD),ER_Total Funding Amount Currency (in USD),ER_Number of Portfolio Organizations,ER_Number of Investments,ER_Number of Lead Investments,ER_Number of Diversity Investments,ER_Number of Lead Investors,ER_Number of Investors
0,2011,Varix Medical acquired by Veniti,Varix Medical,Veniti,Varix Medical,2007,2011.0,Veniti,Health Care,"Health Care, Medical Device, Therapeutics",...,25000000.0,Series D,65220856.0,65220856.0,NaN,NaN,NaN,NaN,4.0,7.0
1,2011,Imperial Global Chauffeur acquired by Fulmer C...,Imperial Global Chauffeur,Fulmer Capital Partners,Imperial Global Chauffeur,2008,2017.0,Star Limousine Services,"Other, Travel and Tourism","Hospitality, Service Industry",...,NaN,NaN,NaN,NaN,34.0,36.0,3.0,NaN,NaN,NaN
2,2011,Unified Dispatch acquired by Transdev,Unified Dispatch,Transdev,Unified Dispatch,2001,2019.0,Resurgent Capital Partners,"Mobile, Transportation","Automotive, Car Sharing, Mobile",...,NaN,Private Equity,NaN,NaN,3.0,4.0,NaN,NaN,NaN,2.0
3,2011,iVisit acquired by NantWorks,iVisit,NantWorks,iVisit,2006,2011.0,NantWorks,"Hardware, Information Technology, Internet Ser...","Messaging, Software, Video Conferencing",...,15000000.0,Venture - Series Unknown,140000000.0,140000000.0,6.0,8.0,4.0,NaN,1.0,1.0
4,2011,Lefa mine acquired by Nordgold,Lefa mine,Nordgold,Lefa mine,2007,2011.0,Nordgold,Natural Resources,Mining,...,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21102,2021,Restorepoint acquired by ScienceLogic,Restorepoint,ScienceLogic,Restorepoint,2008,2021.0,ScienceLogic,"Hardware, Information Technology, Privacy and ...","Data Center Automation, Enterprise Software, N...",...,105000000.0,Series E,189000000.0,214000000.0,NaN,NaN,NaN,NaN,6.0,7.0
21103,2021,Sehlke Consulting acquired by Aeyon,Sehlke Consulting,Aeyon,Sehlke Consulting,2011,2021.0,Aeyon,"Financial Services, Government and Military, I...","Consulting, Financial Services, Government, In...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21104,2021,Homestead Smart Health Plans acquired by 1315 ...,Homestead Smart Health Plans,1315 Capital,Homestead Smart Health Plans,2015,2021.0,1315 Capital,"Administrative Services, Financial Services, H...","Employee Benefits, Health Care, Insurance",...,NaN,NaN,NaN,NaN,5.0,7.0,3.0,1.0,NaN,NaN
21105,2021,The Music Fund acquired by HIFI,The Music Fund,HIFI,The Music Fund,2017,2021.0,HIFI,"Data and Analytics, Financial Services, Media ...","Analytics, Finance, FinTech, Music",...,NaN,Venture - Series Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
21106,2021,Artlin Consulting acquired by Aeyon,Artlin Consulting,Aeyon,Artlin Consulting,2011,2021.0,Aeyon,"Data and Analytics, Media and Entertainment, P...","Advice, Analytics, Management Consulting",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
df.to_excel('..\\data\\new\\Master.xlsx', encoding='utf-8', index=False)